library(ggplot2)
library(dplyr)
library(DT)
library(tidyr)
library(forecast)

## Import

vg_sales <- read.csv("vgsales.csv")

## Data wrangling

vg_sales <- vg_sales[!(vg_sales$Year %in% c("N/A", "2017", "2020")),]

vg_sales <- vg_sales %>% 
  gather(Region, Revenue, 7:10) %>% 
  mutate(Region = as.factor(Region))


## Plots

##Relaseses by Year

ggplot(vg_sales, aes(Year)) + 
  geom_bar(fill = "blue", colour = "black") +
  theme_bw() +
  ggtitle("Video Game Releases by Year")

## Revenues by Year
revenue_by_year <- vg_sales %>% 
  group_by(Year) %>%
  summarize(Revenue = sum(Global_Sales)) 

ggplot(revenue_by_year, aes(Year, Revenue)) + 
  geom_bar(fill = "blue", stat = "identity", colour = "black") +
  theme_bw() +
  ggtitle("Video Game Revenue by Year")

## Top Publishers by Revenue each year

top_publisher_year <- vg_sales %>% 
  group_by(Year, Publisher) %>% 
  summarize(Revenue = sum(Global_Sales)) %>%
  top_n(1)

datatable(top_publisher_year)

ggplot(top_publisher_year, aes(Year, Revenue, fill = Publisher)) + 
  geom_bar(stat = "identity", colour = "black") +
  ggtitle("Top Publisher by Revenue each Year") +
  scale_fill_brewer(palette = "Blues") +
  theme_bw() +
  theme(legend.position = "top")

## Nintendo is the most dominating company.
## EA and Nintendo have 3 decades dominating the market

## Top Genre by Revenue Each Year

top_genre <- vg_sales %>% 
  group_by(Year, Genre) %>% 
  summarize(Revenue = sum(Global_Sales)) %>%
  top_n(1)

datatable(top_genre)

ggplot(top_genre, aes(Year, Revenue, fill = Genre)) + 
  geom_bar(stat = "identity", colour = "black") +
  ggtitle("Top Genre by Revenue each Year") +
  theme_bw() +
  theme(legend.position = "top") +
  scale_fill_brewer(palette = 'YlOrRd')

## In the last 15 years Action is the genre generating most revenues. 

## Top Games by Revenue each Year


top_games <- vg_sales %>%
  group_by(Year, Name) %>%
  summarize(Revenue = sum(Global_Sales)) %>%
  arrange(desc(Revenue)) %>%
  top_n(1)

datatable(top_games)


ggplot(top_games, aes(Year, Revenue, fill = Name)) + 
  geom_bar(stat = "identity", colour = "black") +
  theme_bw() +
  ggtitle("Total Games by Revenue each year") +
  theme(legend.position = "top") 

## 2006 was the best year, with Wii Sports genearting 300M of revenues.

## Top Platform by Revenue Each Year

top_platforms <- vg_sales %>%
  group_by(Year, Platform) %>%
  summarize(Revenue = sum(Global_Sales)) %>%
  arrange(desc(Revenue)) %>%
  top_n(1)

datatable(top_platforms)


ggplot(top_platforms, aes(Year, Revenue, fill = Platform)) + 
  geom_bar(stat = "identity", colour = "black") +
  theme_bw() +
  ggtitle("Top Platform by Revenue each year") +
  theme(legend.position = "top") + 
  scale_fill_brewer(palette = 'YlOrRd')

## We can observe a trend. Once a platform clicks in the market, it rules for a few years.
## Playstation is the most popular. 


## How many publishers are in the market


publishers <- vg_sales %>% 
  group_by(Publisher) %>% 
  summarize(Total = n()) %>% 
  arrange(desc(Total)) %>% 
  head(10) %>% 
  mutate(Percentage = Total/dim(vg_sales)[1] * 100, Publisher = as.factor(Publisher)) 
  

datatable(publishers, filter = "none")


ggplot(publishers, aes(reorder(Publisher, Total), Total, fill = Publisher)) + 
  geom_bar(stat = "identity", colour = "black") + 
  ggtitle("Top 10 Publishers by Number of Releases") + 
  theme(legend.position = "none") + 
  xlab("Publisher") +
  theme_bw() +
  coord_flip()

## EA is the top publisher by releases, Activision 2nd.


## Top publishers by revenue

top_publishers <- vg_sales %>% 
  group_by(Publisher) %>% 
  summarize(Revenue = sum(Global_Sales), Percentage = Revenue/sum(vg_sales$Global_Sales) * 100) %>%
  arrange(desc(Revenue)) %>% 
  head(10) %>%
  mutate(Publisher = factor(Publisher))

datatable(top_publishers)

ggplot(top_publishers, aes(reorder(Publisher, Revenue), Revenue, fill = Publisher)) + 
  geom_bar(stat = "identity", colour = "black") + 
  ggtitle("Top 10 Publishers by Revenue") + 
  theme(legend.position = "none") + 
  xlab("Publisher") +
  ylab("Revenue in millions") +
  theme_bw() +
  coord_flip()


## While EA is the top publisher by releases, Nintendo is the top 1 by revenue, having almost 21% of overall revenue.
## Nearly 70% of overall revenue is generated by the top 10 publishers.

## How the top 10 publishers have grown over the years in terms of releases.

top_publishers <- vg_sales[vg_sales$Publisher %in% publishers$Publisher,] %>% 
  group_by(Publisher, Year) %>% 
  summarize(Total= n())

top_publishers$Publisher <- factor(top_publishers$Publisher)

ggplot(top_publishers, aes(Year, Publisher, fill = Total)) + 
  geom_tile(color = "white") + 
  theme_bw() +
  ggtitle("Top 10 Publishers Releases by Year") +
  xlab("Year") +
  theme(legend.position = "top")

## EA has the highest number of releases between 2002 and 2011. 
## Activision is in the market from 1980.

## How the top 10 publishers have grown over the years in terms of revenue.

top_publishers <- vg_sales[vg_sales$Publisher %in% publishers$Publisher,] %>% 
  group_by(Publisher, Year) %>% 
  summarize(Revenue = sum(Global_Sales))

top_publishers$Publisher <- factor(top_publishers$Publisher)

ggplot(top_publishers, aes(Year, Publisher, fill = Revenue)) + 
  geom_tile(color = "white") + 
  theme_bw() +
  ggtitle("Top 10 Publishers by Revenue") +
  xlab("Year") +
  theme(legend.position = "top")


## Nintendo had the best year in 2006. 
## Nintendo, EA and Activision have been the bests in term of revenues over the last 15 years.


## Genres by Number of Releases

genres <- vg_sales %>% 
  group_by(Genre) %>% 
  summarize(Total = n(), Percentage = Total/dim(vg_sales)[1] * 100) %>%  
  arrange(desc(Percentage))

datatable(genres)

ggplot(genres, aes(reorder(Genre, -Percentage), Percentage, fill = Genre)) + 
  geom_bar(stat = "identity", colour = "black") +
  ggtitle("Video Games Genres by Number of Releases") +
  ylab("Percentage") +
  xlab("Genres") +
  theme(legend.position = "none") + 
  theme_bw()

## Action games have the 20% of the market, sports 14%. 
## Top 5 genres contribute to 60% of games released.


## Genres by Revenue

genres <- vg_sales %>% 
  group_by(Genre) %>% 
  summarize(Revenue = sum(Global_Sales), Percentage = Revenue/sum(vg_sales$Global_Sales) * 100) %>%  
  arrange(desc(Percentage))

datatable(genres)


ggplot(genres, aes(reorder(Genre, -Revenue), Revenue, fill = Genre)) + 
  geom_bar(stat = "identity", colour = "black") +
  ggtitle("Video Games Genres by Revenue") +
  ylab("Revenue in Millions") +
  xlab("Genres") +
  theme(legend.position = "none") + 
  theme_bw()


## Top 10 games by revenue

top_games <- vg_sales %>%
  group_by(Name) %>%
  summarize(Revenue = sum(Global_Sales), Percentage = Revenue/sum(vg_sales$Global_Sales) * 100) %>%
  arrange(desc(Revenue)) %>%
  head(10)

datatable(top_games)

ggplot(top_games, aes(reorder(Name, Revenue), Revenue, fill = Name)) + 
  geom_bar(stat = "identity", colour = "black") +
  ggtitle("Top 10 Games by Revenue") +
  ylab("Revenue in Millions") +
  xlab("Games") +
  theme_bw() +
  theme(legend.position = "none") +
  coord_flip()

## Wii Sports game has 1% of the total revenue with 82.74 million
## Grand Theft Auto V coming second with 55.92 million

## Sales by Region

regions <- vg_sales %>% 
  group_by(Region) %>%
  summarize(TotalRevenue = sum(Revenue), Percentage = TotalRevenue/sum(vg_sales$Revenue) * 100) %>%
  arrange(desc(TotalRevenue))

datatable(regions)

ggplot(regions, aes(Region, TotalRevenue, fill = Region)) + 
  geom_bar(stat = "identity", colour = "black") +
  theme_bw() +
  ggtitle("Total Revenue by Region") +
  theme(legend.position = "top") +
  scale_fill_brewer(palette = "Blues")

## North America has the 49% of total revenues, Europe has 27%.


## Distribution of Sales by Region

ggplot(vg_sales, aes(Region, Revenue, fill = Region)) + 
  geom_boxplot() +
  scale_y_log10() +
  theme_bw() +
  ggtitle("Distribution of Sales Revenue") +
  theme(legend.position = "top") +
  coord_flip()


## Distribution of Sales Revenue by Year

ggplot(vg_sales, aes(Year, Revenue)) + 
  geom_boxplot(fill = "#AA3929") +
  scale_y_log10() +
  theme_bw() +
  ggtitle("Distribution of Sales Revenue - Year") +
  theme(legend.position = "top") +
  coord_flip()

## Sales Revenue by regions and year

by_region_year <- vg_sales %>% 
  group_by(Year, Region) %>%
  summarize(TotalRevenue = sum(Revenue)) %>%
  arrange(desc(TotalRevenue))
by_region_year$Region <- factor(by_region_year$Region)
by_region_year$Year <- factor(by_region_year$Year)

datatable(by_region_year)

ggplot(by_region_year, aes(Year, TotalRevenue, color = Region)) +
  geom_point(size = 3) +
  theme_bw() +
  ggtitle("Total Revenue by Region and Year") +
  theme(legend.position = "top")

## Huge fall in revenue in last 5-6 years. Major fall is in North America


year_genre <- vg_sales %>% 
  group_by(Year, Genre) %>% 
  summarise(TotalRevenue = sum(Revenue)) 

ggplot(year_genre, aes(Genre, Year, fill = TotalRevenue)) +
  geom_tile(color = "white") +
  ggtitle("Total Revenue by Year and Genre") + 
  theme_bw()


# Forecast
df_ts = ts(revenue_by_year$Revenue, start = 1980, frequency = 1)
h = 5
.lambda = 0

pred.arima <- forecast(auto.arima(df_ts, seasonal = T, biasadj=F, lambda = .lambda), h = h)
pred.ets <- forecast(ets(df_ts, lambda = .lambda, biasadj=F), h = h)
pred.nnar <- forecast(nnetar(df_ts, lambda = .lambda, biasadj=F), h=h)
pred.tbats <- forecast(tbats(df_ts, lambda = .lambda, biasadj=F), h=h)
pred.agg <- (pred.ets[["mean"]] + pred.arima[["mean"]]  + pred.nnar[["mean"]] + pred.tbats[["mean"]])/4


